### ISSUE TITLE
Reference list needs more contrast

### ISSUE THREAD

**Issue by thekarel** [b3nk3/hotline-vice-vscode-theme#1]
Lovely theme, thank you!

The "Find references" menu could use a bit more contrast IMO as the current selection is kind of hard to see:

<img width="331" alt="vice" src="https://user-images.githubusercontent.com/2061333/137894987-4fcbf76d-e0a7-46b3-969d-12840e603282.png">
 
Compare it to another theme:

<img width="331" alt="bluloco" src="https://user-images.githubusercontent.com/2061333/137895010-91b843eb-bb14-4eff-8c3a-bb97b45064dc.png">

**Comment by b3nk3** [comment]
Hey, thanks for the feedback. I'll take a look in the coming weeks and try and push a fix for it. 👍🏻

**Comment by b3nk3** [comment]
Hey @thekarel, I have made some imporvements, but am struggling with `vsce` login into my publisher account, and am unable to publish the changes. As soon as I manage to do that I'll be deploying a new version.

Here's a preview tho

<img width="284" alt="image" src="https://user-images.githubusercontent.com/10125940/141286321-5d763a3f-69a0-431f-835e-fac55b169f44.png">

**Comment by b3nk3** [comment]
Published.

**Comment by thekarel** [comment]
That's brilliant, thank you! Now my VSCode is all retro again 😻
